
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BooksExchange.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PostsGenera
{

    public int id { get; set; }

    public int post_id { get; set; }

    public int genera_id { get; set; }



    public virtual Genera Genera { get; set; }

    public virtual Post Post { get; set; }

}

}
